config/routes.rb
Rails.application.routes.draw do

  # Get login token from Knock
  post 'user_token' => 'user_token#create'

  #User routes
  get '/user/current' => 'users#current'

  resources :post_photos_users
  root to: "posts#index"

  #Session routes:
  get '/login' => 'session#new' # login form
  # form submits here, do auth & create sssion & redirect, or show form with errors
  post '/login' => 'session#create'
  delete '/login' =>'session#destroy' # logout, i.e. delete session for this users.
  resources :posts do
    resources :comments
  end

  resources :comments

  resources :post_photos

  resources :follows

  resources :posts

  #need custom destroy route because we arent relying on the like id.
  delete '/likes' => 'likes#destroy'
  resources :likes, except: [:destroy]

  delete '/dislikes' => 'dislikes#destroy'
  resources :dislikes, except: [:destroy]


  #Users CRUD:
  resources :users
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
  resources :posts_users
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord

  has_secure_password
  has_many :posts
  has_many :post_photos
  has_many :follows
  has_many :comments, :through => :posts
  has_many :likes, dependent: :destroy
  # has_many :dislikes, dependent: :destroy
  validates :name, length: { minimum: 2, nmaximum: 20 }
  validates :email, presence: true, uniqueness: true
  validates_presence_of :profile_pic
  private


  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow', dependent: :destroy

  has_many :following, through: :followed_users, source: 'followed'

  has_many :following_users,  class_name: 'Follow', foreign_key: :followed_id, dependent: :destroy

  has_many :followers, through: :following_users, source: 'follower'


  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :verify_authenticity_token
  before_action :check_if_logged_in, except: [:new, :create]
  # before_action :check_if_admin, except: [:show, :new, :edit, :update, :destroy]

  def current
    render json: current_user
  end

  def follow
    @user = User.find(params[:id])
    @current_user.following << @user
    redirect_back(fallback_location: user_path(@user))
  end

  def posts
    @posts = Post.all
  end

  def unfollow
    @user = User.find(params[:id])
    @current_user.followed_users.find_by(followed_id: @user.id).destroy
    redirect_back(fallback_location: user_path(@user))
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    # render json:User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if params[:file].present?
      # actually forward uploaded file on to Cloudinary server
      response = Cloudinary::Uploader.upload params[:file]
      @user.profile_pic = response['public_id']
    end
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :email, :profile_pic, :admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, html: {multipart: true}) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :name, :class=>'form-control', :placeholder => 'Name' %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :email, :class=>'form-control', :placeholder => 'Email' %>
  </div>

  <div class="field">
    <%= form.label :profile_pic %>
      <%= cl_image_upload_tag :user_photo, :class=>'form-control profile_pic' %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, :class=>'form-control', :placeholder => 'Password'   %>
  </div>
  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, :class=>'form-control' , :placeholder => 'Confirm password'  %>
  </div>


  <div class="field">
    <% if @current_user.present? && @current_user.admin %>
    <%= form.label :admin %>
    <%= form.check_box :admin, :class=>'form-check-input' %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<br>
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Deactivate Account', method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-danger btn-sm'  %>|
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
<br>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User profiles</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

      <div class="users-index">

        <% @users.each do |user| %>
          <%= user.name %>        

          <%= link_to user_path(user.id) do %>

            <img class="avatar" src="<%= user.profile_pic %>" alt="">
          <% end%>

        <% end %>

      </div>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/new.js.erb
$('#all-links a').parent().html("<%= j render 'form', user: @user %>")
$('.edit').bind('ajax:success')

app/views/users/show.html.erb
<div class="users_show_left">
  <p id="notice"><%= notice %></p>


  <h5>
    <strong>Name:</strong>
    <%= @user.name %>
  </h5>
  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  <p>
    <img src="<%= @user.profile_pic %>" alt="profile_pic">
  </p>

  <div id="all-links">
    <% if @user.id == @current_user.id %>
      <%= link_to "Edit Profile", edit_user_path, method: :GET %>
    <% elsif @current_user.following.include?(@user) %>
      <h5><%= button_to "Unfollow", unfollow_user_path, method: "POST" %></h5>
    <% else %>
      <h5><%= button_to "Follow", follow_user_path, method: "POST"  %></h5>
    <% end%>
    <h3>Followers</h3>
    <% @user.followers.each do |f| %>
    <p> <%= f.name %> </p>
    <% end %>
    <br>
  </div>

  <%= link_to 'Back', users_path %>
</div>