config/routes.rb
Rails.application.routes.draw do

  # Get login token from Knock
  post 'user_token' => 'user_token#create'

  #User routes
  get '/user/current' => 'users#current'

  resources :post_photos_users
  root to: "posts#index"

  #Session routes:
  get '/login' => 'session#new' # login form
  # form submits here, do auth & create sssion & redirect, or show form with errors
  post '/login' => 'session#create'
  delete '/login' =>'session#destroy' # logout, i.e. delete session for this users.
  resources :posts do
    resources :comments
  end

  resources :comments

  resources :post_photos

  resources :follows

  resources :posts

  #need custom destroy route because we arent relying on the like id.
  delete '/likes' => 'likes#destroy'
  resources :likes, except: [:destroy]

  delete '/dislikes' => 'dislikes#destroy'
  resources :dislikes, except: [:destroy]


  #Users CRUD:
  resources :users
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
  resources :posts_users
end

app/models/post_photo.rb
class PostPhoto < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user, optional: true
  # has_many :likes, dependent: :destroy
  # has_many :dislikes, dependent: :destroy
  has_many :comments
  validates_presence_of :photo

  def likes
    Like.where(target_id:self.id, target_type:'post_photo')
  end

  def dislikes
    Dislike.where(target_id:self.id, target_type:'post_photo')
  end

  def already_disliked_by?(user)
    Dislike.where(user:user, target_id:self.id, target_type:'post_photo').any?
  end

  def already_liked_by?(user)
    Like.where(user:user, target_id:self.id, target_type:'post_photo').any?
  end

end

app/controllers/post_photos_controller.rb
class PostPhotosController < ApplicationController
  before_action :set_post_photo, only: [:show, :edit, :update, :destroy]

  # GET /post_photos
  # GET /post_photos.json
  def index
    @post_photos = PostPhoto.all
    # render json:Post.all
    # render json:PostPhoto.all
  end

  # GET /post_photos/1
  # GET /post_photos/1.json
  def show
  end

  # GET /post_photos/new
  def new
    @post_photo = PostPhoto.new
    # render json:PostPhoto.all
  end

  # GET /post_photos/1/edit
  def edit
  end

  # POST /post_photos
  # POST /post_photos.json
  def create

      if params[:images].present?
        params[:images].each do |image|
          req = Cloudinary::Uploader.upload(image)
          p image
          p req
          @post_photo = PostPhoto.new
          @post_photo.photo = req['public_id']
          if params[:post][:id].present?
            @post_photo.post_id = params[:post][:id]
          end
          @post_photo.user_id = @current_user.id
          puts "??????????????????????????????????????????????POST PHOTO????????????????????"
          p @post_photo

          @post_photo.save

          #TODO check whether each photo actually saved.
        end
      end


    respond_to do |format|
      if @post_photo.persisted?
        format.html do
          if params[:post][:id].present?
            #if a post id was specified in the form drop down, We assume that multiple photos were uploaded
            #so we redirect to the parent post show page of those photos.
            redirect_to post_path(params[:post][:id]), notice: 'Photos successfully added to Post.'
          else
            #if no post id was specified we assume this was a standalone photo upload without a parent post,
            #so we redirect to the photo show page.
            redirect_to @post_photo, notice: 'Post photo was successfully created.'
          end
        end
        format.json { render :show, status: :created, location: @post_photo }
      else
        format.html { render :new }
        format.json { render json: @post_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_photos/1
  # PATCH/PUT /post_photos/1.json
  def update
    respond_to do |format|
      if @post_photo.update(post_photo_params)
        format.html { redirect_to @post_photo, notice: 'Post photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_photo }
      else
        format.html { render :edit }
        format.json { render json: @post_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_photos/1
  # DELETE /post_photos/1.json
  def destroy
    @post_photo.destroy
    respond_to do |format|
      format.html { redirect_to post_photos_url, notice: 'Post photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_photo
      @post_photo = PostPhoto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_photo_params
      params.require(:post_photo).permit(:photo)
    end
end

app/helpers/post_photos_helper.rb
module PostPhotosHelper
end

app/views/post_photos/_form.html.erb
<div class="form-group">

  <%= form_with(model: post_photo, local: true, html: {multipart: true}) do |form| %>
    <% if post_photo.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post_photo.errors.count, "error") %> prohibited this post_photo from being saved:</h2>

        <ul>
        <% post_photo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= label_tag :post %>
        <%= collection_select(:post, :id, @current_user.posts, :id, :user_post, prompt: true) %>
    </div>

    <div class="field">
      <%= form.label :photo %>
        <%# cl_image_upload_tag :user_photo %>
        <%= file_field_tag "images[]", :multiple => true %>
    </div>

    <div class="actions">
      <%= form.submit :class=>'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/post_photos/edit.html.erb
<h3>Edit Post Photo</h3>

<%= render 'form', post_photo: @post_photo %>

<%= link_to 'Show', @post_photo %> |
<%= link_to 'Back', post_photos_path %>

app/views/post_photos/index.html.erb
<p id="notice"><%= notice %></p>

<div class="btn btn-dark creation">
  <%= link_to 'New Post Photo', new_post_photo_path %>
</div>

<div class="feed">
  <% @post_photos.each do |post_photo| %>
    <div class="post">
      <div>
        <p><%= post_photo.user.name %></p>
      </div>
      <div class="feed_header">
        <%= cl_image_tag(post_photo.photo, :class=>'post-image') %>

        <p class="card-text">
          <small class="text-muted">Last updated <%= post_photo.updated_at %></small>
        </p>

    </div>
    <% end%>
  </div>

app/views/post_photos/new.html.erb
<h3>New Post Photo</h3>

<%= render 'form', post_photo: @post_photo %>

<%= link_to 'Back', post_photos_path %>

app/views/post_photos/show.html.erb
<%= link_to 'Back', post_photos_path %>
<% if @current_user.present? && @current_user.admin %>
  <td><%= link_to 'Edit', edit_post_photo_path(@post_photo) %> </td>
  <td><%= link_to 'Destroy', @post_photo, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-danger btn-sm'  %></td>
<% end %>


<p id="notice"><%= notice %></p>

<div>
  <strong>Photo:</strong>
  <%= cl_image_tag @post_photo.photo %>
  <p><%= @post_photo.likes.count %> <%= (@post_photo.likes.count) == 1 ? 'Like' : 'Likes'%></p>

  <% if @post_photo.already_liked_by?(@current_user) %>
  <%= button_to 'Unlike', likes_path, method: :delete, params: {target_type:'post_photo', target_id:@post_photo.id} %>
  <% else %>
  <%= button_to 'Like', likes_path, method: :post, params: {target_type:'post_photo', target_id:@post_photo.id} %>
  <% end %>

  <p><%= @post_photo.dislikes.count %> <%= (@post_photo.dislikes.count) == 1 ? 'Dislike' : 'Dislikes'%></p>

  <% if @post_photo.already_disliked_by?(@current_user) %>
  <%= button_to 'Undislike', dislikes_path, method: :delete, params: {target_type:'post_photo', target_id:@post_photo.id} %>
  <% else %>
  <%= button_to 'Dislike', dislikes_path, method: :post, params: {target_type:'post_photo', target_id:@post_photo.id} %>
  <% end %>
</div>