config/routes.rb
Rails.application.routes.draw do

  # Get login token from Knock
  post 'user_token' => 'user_token#create'

  #User routes
  get '/user/current' => 'users#current'

  resources :post_photos_users
  root to: "posts#index"

  #Session routes:
  get '/login' => 'session#new' # login form
  # form submits here, do auth & create sssion & redirect, or show form with errors
  post '/login' => 'session#create'
  delete '/login' =>'session#destroy' # logout, i.e. delete session for this users.
  resources :posts do
    resources :comments
  end

  resources :comments

  resources :post_photos

  resources :follows

  resources :posts

  #need custom destroy route because we arent relying on the like id.
  delete '/likes' => 'likes#destroy'
  resources :likes, except: [:destroy]

  delete '/dislikes' => 'dislikes#destroy'
  resources :dislikes, except: [:destroy]


  #Users CRUD:
  resources :users
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
  resources :posts_users
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_photos
  has_many :comments

  # has_and_belongs_to_many :liked_by_users, class_name:'User'
  # has_and_belongs_to_many :disliked_by_users, class_name:'User'


  def likes
    Like.where(target_id:self.id, target_type:'post')
  end

  def dislikes
    Dislike.where(target_id:self.id, target_type:'post')
  end

  def already_disliked_by?(user)
    Dislike.where(user:user, target_id:self.id, target_type:'post').any?
  end

  def already_liked_by?(user)
    Like.where(user:user, target_id:self.id, target_type:'post').any?
  end

  def updated_date_formatted
    # TODO : add this method to the post updated date
    self.updated_date.strftime("%d %b %Y, %I:%M%P")
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # before_action :check_if_logged_in, except: [:show, :index ]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    # render json:Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json

  def create
    @post = Post.new(post_params)
    # TODO remove this security nightmare
    # only here for testing react frontend beofre logins working
    if @current_user.present? 
      @post.user_id = @current_user.id 
    else 
      ## hard-coded userid for react
      @post.user_id = User.first.id 
    end
    @post.save

       # Handle upload, if file was uploaded
    if params[:file].present?
      # actually forward uploaded file on to Cloudinary server
      response = Cloudinary::Uploader.upload params[:file]
      @post.user_photo = response['public_id']
      @post.save
    end

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: {
          post: @post,
          success: true
        } 
      }
      else
        format.html { render :new }
      end
    end
  end #create

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_post, :user_photo)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="form-group">
    <%= form_for post, html: {multipart: true} do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <br>
    <br>
    <div class="field">
      <%= form.text_area :user_post, :class=>'form-control', :placeholder => 'Tell the world of your troubles here' %>
    </div>
    <br>
    <br>
    <div class=actions>
        <%= cl_image_upload_tag :user_photo %>
        <br>
        <br>
    </div>
    <br>
    <div class="actions">
      <%= form.submit :class=>'btn btn-secondary' %>
    </div>
    <% end %>

</div>

app/views/posts/edit.html.erb
<br>
<h3>Edit Post</h3>

<%= render 'form', post: @post %>
<br>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>|
<%= link_to 'Delete Post', method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-danger btn-sm'  %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="btn btn-dark">
  <%= link_to 'New Post', new_post_path %>
</div>
<br>
<div class="feed">
  <%#  Loops through each post, @posts can be found in the controller action 'index' for posts, and inside the loop we use the association of the post to the user it belongs to, to print out some information about the user who made the post(e.g. post.user.name, id.. profile_photo 01) and also the content o fhte post : post.user_post 
  TODO : remove user_ prefix from post fields. 
  %>
  <% @posts.each do |post| %>
    <div class="post">
      <div class="avatar-container">
      <%# Print link to user's profile page.       %>
        <%= link_to user_path(post.user.id) do %>
          <img class="avatar" src="<%= post.user.profile_pic %>" alt="<%= post.user_post %>">
        <% end%>
        <p><%= post.user.name %></p>
      </div>
      <div>
        <p><%= post.user_post %></p>
      <%# Added link to the show page for the particular post, post_path helper generates a link like "/posts/:id" handled by posts#show  %>
          <%= link_to post_path(post.id) do %>
            <%= cl_image_tag(post.user_photo, :class=>'post-image') %>
          <% end %>
        <p class="card-text">
          <small class="text-muted">Last updated <%= post.updated_at %></small>
        </p>
      </div>

    </div>

    <%# Like, dislike buttons shouldn't show unless user is logged in: %>
    <% if @current_user.present? %>

      <%# Displays the number of likes for the particular post. %>
      <div class="likes-posts">
        <%= post.likes.count %> 
        :
        <%# If post has already been liked or disliked, displays an unlike or like button respectively %>
        <% if post.already_liked_by?(@current_user) %>
          <%= button_to 'Unlike', likes_path, method: :delete, params: {target_type:'post', target_id:post.id} %>
        <% else %>
        <%# If post has been unliked, displays like button %>
          <%= button_to 'Like', likes_path, method: :post, params: {target_type:'post', target_id:post.id} %>
        <% end %>
        <%# Shows number of dislikes %>
        <%= post.dislikes.count %> <%= (post.dislikes.count) == 1 ? '' : ''%>
        :

        <% if post.already_disliked_by?(@current_user) %>
          <%= button_to 'Undislike', dislikes_path, method: :delete, params: {target_type:'post', target_id:post.id} %>
        <% else %>
          <%= button_to 'Dislike', dislikes_path, method: :post, params: {target_type:'post', target_id:post.id} %>
        <% end %>
    
        <div class="comments">
        <%= render post.comments %>
        </div>
    <% end %>
    </div>
  <% end%>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post%>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<br>
<%= link_to 'Back', posts_path %>
<!-- Checks whether the user logged in is an admin and shows admin functionality if so.-->
<% if @current_user.present? && @current_user.admin %>
  <td><%= link_to 'Edit', edit_post_path(@post), :class=>'btn btn-secondary btn-sm' %></td>
  <td><%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-danger btn-sm'  %></td>
<% end %>


<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post.user_post %>
</p>

<%= cl_image_tag @post.user_photo, :class=>'post-image' %>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<%# Show number of likes for the page and pluralizes 'like' using the ruby inbuilt function %>
<p><%= @post.likes.count 'Like'.pluralize %>

 <%= (@post.likes.count) == 1 ? 'Like' : 'Like'.pluralize %></p>
<%#  %>
<% if @post.already_liked_by?(@current_user) %>
  <%= button_to 'Unlike', likes_path, method: :delete, params: {target_type:'post', target_id:@post.id} %>
<% else %>
  <%= button_to 'Like', likes_path, method: :post, params: {target_type:'post', target_id:@post.id} %>
<% end %>

<p><%= @post.dislikes.count %> <%= (@post.dislikes.count) == 1 ? 'Dislike' : 'Dislikes'%></p>
<% if @post.already_disliked_by?(@current_user) %>
<%= button_to 'Undislike', dislikes_path, method: :delete, params: {target_type:'post', target_id:@post.id} %>
<% else %>
<%= button_to 'Dislike', dislikes_path, method: :post, params: {target_type:'post', target_id:@post.id} %>
<% end %>
<hr/>

<div>
  <p><strong><%= @post.comments.count%></strong> Comments</p>
  <%= render @post.comments %>
  <div class="col-7">
    <p class="subtitle is-3">Add a comment<p>
      <%= render 'comments/form' %>
  </div>
</div>