config/routes.rb
Rails.application.routes.draw do

  # Get login token from Knock
  post 'user_token' => 'user_token#create'

  #User routes
  get '/user/current' => 'users#current'

  resources :post_photos_users
  root to: "posts#index"

  #Session routes:
  get '/login' => 'session#new' # login form
  # form submits here, do auth & create sssion & redirect, or show form with errors
  post '/login' => 'session#create'
  delete '/login' =>'session#destroy' # logout, i.e. delete session for this users.
  resources :posts do
    resources :comments
  end

  resources :comments

  resources :post_photos

  resources :follows

  resources :posts

  #need custom destroy route because we arent relying on the like id.
  delete '/likes' => 'likes#destroy'
  resources :likes, except: [:destroy]

  delete '/dislikes' => 'dislikes#destroy'
  resources :dislikes, except: [:destroy]


  #Users CRUD:
  resources :users
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
  resources :posts_users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post, optional:true
    belongs_to :users, optional: true
    belongs_to :post_photo, optional:true
    # has_many :likes
    # has_many :dislikes


    def likes
      Like.where(target_id:self.id, target_type:'comment')
    end

    def dislikes
      Dislike.where(target_id:self.id, target_type:'comment')
    end

    def already_disliked_by?(user)
      Dislike.where(user:user, target_id:self.id, target_type:'comment').any?
    end

    def already_liked_by?(user)
      Like.where(user:user, target_id:self.id, target_type:'comment').any?
    end
end

app/models/dislike.rb
class Dislike < ApplicationRecord
  belongs_to :post, optional:true
  belongs_to :user
  belongs_to :comment, optional:true
  belongs_to :post_photo, optional: true
  enum target_type: [:post,:post_photo,:comment]
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, uniqueness: { scope: :followed_id }
  validates :followed_id, uniqueness: { scope: :follower_id }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, optional:true
  belongs_to :user
  belongs_to :comment, optional:true
  belongs_to :post_photo, optional:true
  enum target_type: [:post,:post_photo,:comment]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_photos
  has_many :comments

  # has_and_belongs_to_many :liked_by_users, class_name:'User'
  # has_and_belongs_to_many :disliked_by_users, class_name:'User'


  def likes
    Like.where(target_id:self.id, target_type:'post')
  end

  def dislikes
    Dislike.where(target_id:self.id, target_type:'post')
  end

  def already_disliked_by?(user)
    Dislike.where(user:user, target_id:self.id, target_type:'post').any?
  end

  def already_liked_by?(user)
    Like.where(user:user, target_id:self.id, target_type:'post').any?
  end

  def updated_date_formatted
    # TODO : add this method to the post updated date
    self.updated_date.strftime("%d %b %Y, %I:%M%P")
  end


end

app/models/post_photo.rb
class PostPhoto < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user, optional: true
  # has_many :likes, dependent: :destroy
  # has_many :dislikes, dependent: :destroy
  has_many :comments
  validates_presence_of :photo

  def likes
    Like.where(target_id:self.id, target_type:'post_photo')
  end

  def dislikes
    Dislike.where(target_id:self.id, target_type:'post_photo')
  end

  def already_disliked_by?(user)
    Dislike.where(user:user, target_id:self.id, target_type:'post_photo').any?
  end

  def already_liked_by?(user)
    Like.where(user:user, target_id:self.id, target_type:'post_photo').any?
  end

end

app/models/post_photos_user.rb
class PostPhotosUser < ApplicationRecord
  enum vote_photos: [:likes, :dislike]
end

app/models/posts_user.rb
class PostsUser < ApplicationRecord
  enum vote_posts: [:likes, :dislike]
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord

  has_secure_password
  has_many :posts
  has_many :post_photos
  has_many :follows
  has_many :comments, :through => :posts
  has_many :likes, dependent: :destroy
  # has_many :dislikes, dependent: :destroy
  validates :name, length: { minimum: 2, nmaximum: 20 }
  validates :email, presence: true, uniqueness: true
  validates_presence_of :profile_pic
  private


  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow', dependent: :destroy

  has_many :following, through: :followed_users, source: 'followed'

  has_many :following_users,  class_name: 'Follow', foreign_key: :followed_id, dependent: :destroy

  has_many :followers, through: :following_users, source: 'follower'


  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dislikes_helper.rb
module DislikesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_photos_helper.rb
module PostPhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social media app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= cloudinary_js_config %>


    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to root_path do %>
        <div>
          <%= image_tag("logo.png", :class=>'logo') %>
        </div>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul>
          <% if @current_user.present? %>
            <li>
              Hello, <%= @current_user.name %> |
              <%= link_to 'Logout', login_path, method: 'delete' %>
            </li>
            <li class="nav-link">
              <%= link_to 'FEED', posts_path %>
            </li>
            <li class="nav-link">
              <%= link_to 'PHOTOS', post_photos_path %>
            </li>
        <li class="nav-link">
          <%= link_to 'PROFILES', users_path %>
        </li>

        <%  elsif @current_user.present? && @current_user.admin === true%>
          <li class="nav-link">
          <i class="fas fa-user-plus"></i>
            <%= link_to 'Create user', new_user_path %>
          </li>

          <% else %>
          <li class="nav-link">
            <%= link_to 'LOGIN', login_path %>
          </li>
           <li class="nav-link">
            <%= link_to 'FEED', posts_path %>
          </li>
          <li class="nav-link">
            <%= link_to 'PHOTOS', post_photos_path %>
          </li>
        </ul>
        <% end %>
        </div>
      </nav>

      <div class="container">
        <%= yield %>
      </div>


  </body>
</html>

app/views/pages/home.html.erb
<p>Welcome to the social media app landing page</p>

<p>Click the link above to sign in  </p>

<br>
<br>

app/views/pages/welcome.html.erb
<h1>Welcome to Touch</h1>
<br>
<%= link_to 'Click here to login', login_path %>